
FIND_PATH(GLFW_INCLUDE_DIRS NAMES GLFW/glfw3.h)

FIND_LIBRARY(GLFW_LIBRARIES NAMES glfw3 glfw)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLFW DEFAULT_MSG GLFW_LIBRARIES GLFW_INCLUDE_DIRS)